version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

python:
  install:
    - requirements: docs/requirements.txt
    # Install our python package before building the docs
    # 在构建文档之前安装我们的python包
    # 现在，Read the Docs 将安装 Python 代码 在开始 Sphinx 构建之前，它将无缝完成。
    - method: pip
      path: .

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true

# formats:
#   - pdf
#   - epub